#! /bin/sh

eval $(ssh-agent)

xrandr --output DisplayPort-0 \
  --primary \
  --mode 2560x1440 \
  --rate 165 \
  --output HDMI-A-0 \
  --left-of DisplayPort-0 \
  --rotate left \
  --auto

numlockx on
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true
bspc config focused_border_color  \#CD7D4C
bspc config active_border_color   \#1c0533
bspc config normal_border_color   \#1c0533

sh ~/.fehbg

xsetroot -cursor_name left_ptr
sxhkd &
dunst &

# xrdb -merge ~/.config/rofi/rofi

bspc rule -a Plasma state=floating manage=off layer=normal
bspc rule -a Plasma-desktop state=floating manage=off layer=normal
bspc rule -a plasmashell state=floating sticky=off border=off center=off
bspc rule -a plasmashell state=floating border=off layer=above center=off manage=off

bspc monitor DisplayPort-0 -d 1 2 3 4
bspc monitor DisplayPort-1 -d 5 6 7 8
bspc monitor HDMI-A-0 -d 5 6 7 8
bspc wm -O DisplayPort-0 DisplayPort-1
bspc wm -O DisplayPort-0 HDMI-A-0
